RESIDENTS = {
'1': '',
'abdulla': 'abdullas',
'agh': '',
'belair': 'jeffbelair',
'benjamin': 'Benjaminjc',
'bloom': 'bloomdg',
'boonsiri': 'boonsiriji',
'borhani': 'borhaniaa',
'busselberg': '',
'chang -sen': 'LChangSen',
'chang sen': 'LChangSen',
'chang-sen': 'LChangSen',
'chen': 'chenss',
'charter': 'charterns',
'ching': 'kc41784',
'chu': 'chue',
'ding': 'mppding',
'faber': 'faberlf',
'fargiano': 'Tony',
'fragiano': 'Tony',
'fetzer': 'fetzerdt',
'fitzgerald': '',
'freed': 'freedrj',
'gallagher': 'deirdre',
'granville': '',
'guluzian': 'guluzianj',
'haldipur': 'haldipurag',
'haringrekar': 'haringrekar',
'hill': 'Hillgc',
'hooper': 'daniellehooper',
'howell': 'howellmc',
'hsu': 'hsua',
'hunnicutt': 'hunnicuttct',
'houshmand': 'Houshmandg',
'hwang': 'hwangm2',
'jacobs': 'jacobsbc2',
'khanna': 'khannavk',
'kantartzis': 'stamatis',
'koo': 'koojj',
'lee': 'leeka',
'leeman j': 'leemanjj',
'leemanj': 'leemanjj',
'leeman k': 'leemanka',
'leemank': 'leemanka',
'livingston': 'livingstonjg',
'long': 'longjd',
'mannava': 'mannavar',
'mcgreevy': 'mcgreevybp',
'medsinge': '',
'mezger': 'mezgerjc',
'milanovich': 'milanovichnj',
'narignrekar': 'haringrekar',
'naringrekar': 'haringrekar',
'nastasi': '',
'huy': 'nguyenhm',
'nguyen': 'nguyenhm',
'packard': 'mpackard',
'peterson hooper': 'petersonwm',
'peterson': 'petersonwm',
'qu': 'quc',
'reynolds': 'reynoldsar2',
'rhoads': 'wongws',
'rhoads-wong': 'wongws',
'rhodes-wong': 'wongws',
'richardson': 'richardsonbc',
'rodriguez': 'rodriguezd',
'roth': 'rothes',
'rudzinski': 'scottrudzinski',
'ryan': 'alextryan',
'samadi': 'samadif',
'savino': 'savinomr',
'schnor': 'schnorn',
'schwarz': 'schwarzns',
'sechrist': 'sechristjw',
'seynnaeve': 'seynnaeveca',
'sinelnikov': 'sinelnikovas',
'shankar': 'shankarpr',
'sharek': 'daniellehooper',
'sheu': 'sheuy',
'swihart': 'swihart',
'taylor': 'taylorct',
'thomas': 'thomasea016',
'tocchio': 'tocchiosl',
'tsend': 'tsengi',
'tseng': 'tsengi',
'tuel': '',
'tung': 'kawahtung',
'wang/haldipur': 'wangd',
'wang/chang sen': 'wangd',
'wang': 'wangd',
'wiant': 'wiantam',
'wong': 'wongws',
'wong-rhoads': 'wongws',
'woodard': 'woodardjd',
'yeager': 'yaegerk',
'yaeger': 'yaegerk',
'yaegar': 'yaegerk',
'yeagar': 'yaegerk',
}

USERNAMES = [
'jeffbelair',
'bloomdg',
'boonsiriji',
'borhaniaa',
'LChangSen',
'charterns',
'kc41784',
'chue',
'mppding',
'faberlf',
'Tony',
'fetzerdt',
'deirdre',
'guluzianj',
'haldipurag',
'haringrekar',
'Hillgc',
'daniellehooper',
'howellmc',
'hsua',
'hunnicuttct',
'hwangm2',
'jacobsbc2',
'stamatis',
'koojj',
'leeka',
'leemanjj',
'leemanka',
'longjd',
'mcgreevybp',
'mezgerjc',
'milanovichnj',
'nguyenhm',
'mpackard',
'petersonwm',
'richardsonbc',
'rodriguezd',
'rothes',
'scottrudzinski',
'alextryan',
'samadif',
'savinomr',
'schnorn',
'schwarzns',
'shankarpr',
'sheuy',
'swihart',
'thomasea016',
'tocchiosl',
'tsengi',
'kawahtung',
'wangd',
'wiantam',
'wongws',
'woodardjd',
'yaegerk',
]

NAMES = [
'Belair, Jeffrey',
'Boonsiri, Joseph',
'Ching, Kevin',
'Chu, Edwin',
'Howell, Michael',
'Hsu, Ariel',
'Hunnicutt, Christopher',
'Hwang, Misun',
'Naringrekar, Haresh',
'Nguyen, Huy',
'Rodriguez, David',
'Savino, Michael',
'Tocchio, Shannon',
'Yaeger, Karl',
'Chang Sen, Lauren',
'Haldipur, Anshul',
'Jacobs, Benjamin',
'Koo, Julie',
'Leeman, Kimberly',
'Milanovich, Nicholas',
'Roth, Eira',
'Schnor, Nils',
'Shankar, Prasad',
'Tseng, Irene',
'Tung, Ka-wah',
'Wang, David',
'Woodard, Jesse',
'Borhani, Amir',
'Fetzer, David',
'Hill, Geoffrey',
'Hooper, Danielle',
'Leeman, Joshua',
'Long, Jason',
'Mcgreevy, Benjamin',
'Mezger, James',
'Peterson, William',
'Rudzinski, Scott',
'Samadi, Faraz',
'Thomas, Ernestine',
'Wiant, Amanda',
'Wong, Wendy',
'Bloom, Daniel',
'Charter, Nathaniel',
'Fargiano, Antonio',
'Gallagher, Deirdre',
'Guluzian, John',
'Ding, Michelle',
'Faber, Lance',
'Kantartzis, Stamatis',
'Lee, Karen',
'Packard, Michael',
'Richardson, Brett',
'Ryan, Alexander',
'Schwarz, Naomi',
'Sheu, Yun',
'Swihart, Andrew',
]